/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as FlycoachRouteImport } from './routes/flycoach'
import { Route as CourseRouteImport } from './routes/course'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IndexRouteImport } from './routes/index'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const FlycoachRoute = FlycoachRouteImport.update({
  id: '/flycoach',
  path: '/flycoach',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/flycoach': typeof FlycoachRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/flycoach': typeof FlycoachRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/flycoach': typeof FlycoachRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/certificate' | '/course' | '/flycoach' | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/certificate' | '/course' | '/flycoach' | '/simulator'
  id: '__root__' | '/' | '/certificate' | '/course' | '/flycoach' | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  CourseRoute: typeof CourseRoute
  FlycoachRoute: typeof FlycoachRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flycoach': {
      id: '/flycoach'
      path: '/flycoach'
      fullPath: '/flycoach'
      preLoaderRoute: typeof FlycoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  CourseRoute: CourseRoute,
  FlycoachRoute: FlycoachRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
