/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherLabRouteImport } from './routes/weather-lab'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MapLabRouteImport } from './routes/map-lab'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlycoachRouteImport } from './routes/flycoach'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CourseRouteImport } from './routes/course'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminLandingRouteImport } from './routes/admin.landing'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'

const WeatherLabRoute = WeatherLabRouteImport.update({
  id: '/weather-lab',
  path: '/weather-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MapLabRoute = MapLabRouteImport.update({
  id: '/map-lab',
  path: '/map-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlycoachRoute = FlycoachRouteImport.update({
  id: '/flycoach',
  path: '/flycoach',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/lessons/$slug',
  path: '/lessons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flycoach': typeof FlycoachRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson': typeof LessonRoute
  '/map-lab': typeof MapLabRoute
  '/mission': typeof MissionRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/weather-lab': typeof WeatherLabRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flycoach': typeof FlycoachRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson': typeof LessonRoute
  '/map-lab': typeof MapLabRoute
  '/mission': typeof MissionRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/weather-lab': typeof WeatherLabRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/certificate': typeof CertificateRoute
  '/course': typeof CourseRoute
  '/dashboard': typeof DashboardRoute
  '/flashcards': typeof FlashcardsRoute
  '/flycoach': typeof FlycoachRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/lesson': typeof LessonRoute
  '/map-lab': typeof MapLabRoute
  '/mission': typeof MissionRoute
  '/onboarding': typeof OnboardingRoute
  '/practice': typeof PracticeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/weather-lab': typeof WeatherLabRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/landing': typeof AdminLandingRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/lessons/$slug': typeof LessonsSlugRoute
  '/verify/$id': typeof VerifyIdRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/certificate'
    | '/course'
    | '/dashboard'
    | '/flashcards'
    | '/flycoach'
    | '/forgot-password'
    | '/lesson'
    | '/map-lab'
    | '/mission'
    | '/onboarding'
    | '/practice'
    | '/reset-password'
    | '/simulator'
    | '/weather-lab'
    | '/admin/certificates'
    | '/admin/landing'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/lessons/$slug'
    | '/verify/$id'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/certificate'
    | '/course'
    | '/dashboard'
    | '/flashcards'
    | '/flycoach'
    | '/forgot-password'
    | '/lesson'
    | '/map-lab'
    | '/mission'
    | '/onboarding'
    | '/practice'
    | '/reset-password'
    | '/simulator'
    | '/weather-lab'
    | '/admin/certificates'
    | '/admin/landing'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/lessons/$slug'
    | '/verify/$id'
    | '/lessons'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/certificate'
    | '/course'
    | '/dashboard'
    | '/flashcards'
    | '/flycoach'
    | '/forgot-password'
    | '/lesson'
    | '/map-lab'
    | '/mission'
    | '/onboarding'
    | '/practice'
    | '/reset-password'
    | '/simulator'
    | '/weather-lab'
    | '/admin/certificates'
    | '/admin/landing'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/lessons/$slug'
    | '/verify/$id'
    | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CertificateRoute: typeof CertificateRoute
  CourseRoute: typeof CourseRoute
  DashboardRoute: typeof DashboardRoute
  FlashcardsRoute: typeof FlashcardsRoute
  FlycoachRoute: typeof FlycoachRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LessonRoute: typeof LessonRoute
  MapLabRoute: typeof MapLabRoute
  MissionRoute: typeof MissionRoute
  OnboardingRoute: typeof OnboardingRoute
  PracticeRoute: typeof PracticeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulatorRoute: typeof SimulatorRoute
  WeatherLabRoute: typeof WeatherLabRoute
  LessonsSlugRoute: typeof LessonsSlugRoute
  VerifyIdRoute: typeof VerifyIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather-lab': {
      id: '/weather-lab'
      path: '/weather-lab'
      fullPath: '/weather-lab'
      preLoaderRoute: typeof WeatherLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-lab': {
      id: '/map-lab'
      path: '/map-lab'
      fullPath: '/map-lab'
      preLoaderRoute: typeof MapLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flycoach': {
      id: '/flycoach'
      path: '/flycoach'
      fullPath: '/flycoach'
      preLoaderRoute: typeof FlycoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/lessons/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminLandingRoute: typeof AdminLandingRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminLandingRoute: AdminLandingRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CertificateRoute: CertificateRoute,
  CourseRoute: CourseRoute,
  DashboardRoute: DashboardRoute,
  FlashcardsRoute: FlashcardsRoute,
  FlycoachRoute: FlycoachRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LessonRoute: LessonRoute,
  MapLabRoute: MapLabRoute,
  MissionRoute: MissionRoute,
  OnboardingRoute: OnboardingRoute,
  PracticeRoute: PracticeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulatorRoute: SimulatorRoute,
  WeatherLabRoute: WeatherLabRoute,
  LessonsSlugRoute: LessonsSlugRoute,
  VerifyIdRoute: VerifyIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
